name: IGLanguages
version: '${project.version}'
authors: ['IceGames', 'RainBowCreation']
main: me.icegames.iglanguages.IGLanguages
depend: [PlaceholderAPI]
softdepend: [ ProtocolLib ]
commands:
  languages:
    description: Main command of IGLanguages
    usage: /<command> [help|set|get|auto|list|reload]
    aliases: [lang, langs, iglang, iglangs, iglanguages]
permissions:
  iglanguages.admin:
    description: Total access to IGLanguages commands
    default: op