name: IGLanguages
version: '${project.version}'
author: 'IceGames'
main: me.icegames.iglanguages.IGLanguages
depend: [PlaceholderAPI]
commands:
  languages:
    description: Main command of IGLanguages
    usage: /<command> [help|set|get|list|reload]
    aliases: [lang, langs, iglang, iglangs, iglanguages]
permissions:
  iglanguages.admin:
    description: Total access to IGLanguages commands
    default: op